config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  root 'static_pages#top'
  get 'static_pages/top', to: 'static_pages#top', as: 'static_pages_top'
  get 'static_pages/welcome', to: 'static_pages#welcome'
  get 'signup', to: 'users#new'

  resources :users, only: [:show]
  
  namespace :stocks do
    resources :stocks, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :emergency_kits, only: [:index, :show, :create, :edit, :update, :destroy, :new] do
      collection do
        get 'all'
      end
      resources :kit_items, only: [:index, :create, :edit, :update, :destroy] do
      end
    end
  end  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/emergency_kit.rb
class EmergencyKit < ApplicationRecord
  belongs_to :user
  belongs_to :owner, class_name: 'EmergencyKitsOwner'
  has_many :kit_items
  has_one :reminder, dependent: :destroy
  accepts_nested_attributes_for :reminder

  # 定期的にリマインダーを送信
  def self.send_reminders
    # interval_months分経過したリマインダーを送信
    Reminder.where('updated_at <= ?', Time.current - interval_months.months).find_each do |reminder|
      # 対応するユーザーにリマインダーメールを送信
      UserMailer.reminder_email(reminder.emergency_kit.user).deliver_later
    end
  end
end

app/models/emergency_kits_owner.rb
class EmergencyKitsOwner < ApplicationRecord
  belongs_to :user
  has_many :emergency_kits
  
  enum gender: { male: 0, female: 1, other: 2 }
  def gender_i18n
    I18n.t("enums.gender.#{gender}")
  end

  def self.human_enum_name(enum_name, key)
    I18n.t("enums.#{enum_name}.#{key}")
  end
  
  validates :name, presence: true
  validates :age, presence: true
  validates :gender, presence: true
end
  

app/models/item.rb
class Item < ApplicationRecord
  has_many :kit_items, dependent: :destroy
  
  validates :name, presence: true
end
  

app/models/kit_item.rb
class KitItem < ApplicationRecord
  belongs_to :emergency_kit
  has_many :reminders, foreign_key: :stock_item_id
  accepts_nested_attributes_for :reminders, allow_destroy: true # リマインダーをネストできるようにする
end
  

app/models/reminder.rb
class Reminder < ApplicationRecord
  belongs_to :kit_item
  belongs_to :stock_item
  belongs_to :emergency_kit
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :user
  has_many :stock_items, dependent: :destroy 
  accepts_nested_attributes_for :stock_items  # StockItem をネストして受け入れる
  has_many :reminders, through: :stock_items
  accepts_nested_attributes_for :reminders
end

app/models/stock_item.rb
class StockItem < ApplicationRecord
  belongs_to :stock
  has_many :reminders, foreign_key: :stock_item_id
  accepts_nested_attributes_for :reminders, allow_destroy: true  # リマインダーをネストできるようにする

  validates :name, presence: true
end
  

app/models/user.rb
class User < ApplicationRecord
  has_many :stocks
  has_many :emergency_kits
  has_many :emergency_kits_owners
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # サインアップ時にnameを許可
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])

    # アカウント更新時にもnameを許可
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

  

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @reminder = Reminder.new(reminder_params)
    @reminder.user = current_user
  
    if @reminder.save
      redirect_to some_path, notice: 'リマインドが追加されました。'
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def destroy
    @reminder = Reminder.find(params[:id])
    @reminder.destroy
      redirect_to some_path, notice: 'リマインドが削除されました。'
  end
  
  private
  
  def reminder_params
    params.require(:reminder).permit(:kit_item_id, :stock_item_id)
  end
end
  

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
    if user_signed_in?
      # ログイン後は、適切なトップページにリダイレクト
      render 'static_pages/top'
    else
      # ログインしていない場合は、ログイン前のトップページを表示
      render 'static_pages/welcome'
    end
  end
end

app/controllers/stocks/kit_items_controller.rb
class Stocks::KitItemsController < ApplicationController
  before_action :set_emergency_kit
  before_action :set_kit_item, only: [:edit, :update, :show, :destroy]

  def index
    @kit_items = @emergency_kit.kit_items
  end

  def create
    @kit_item = @emergency_kit.kit_items.build(kit_item_params)
    if @kit_item.save
      redirect_to stocks_emergency_kit_path(@emergency_kit), notice: 'Kit item was successfully added.'
    else
      redirect_to stocks_emergency_kit_path(@emergency_kit), alert: 'Failed to add kit item.'
    end
  end
  
  def edit
  end  
  
  def update
    if @kit_item.update(kit_item_params)
      redirect_to stocks_emergency_kit_path(@kit_item.emergency_kit), notice: 'アイテムが更新されました。'
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @kit_item.destroy
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@kit_item) }
      format.html { redirect_to stocks_emergency_kit_path(@kit_item.emergency_kit), notice: "Item was successfully destroyed." }
    end
  end
  
  
  private
  
  def set_emergency_kit
    @emergency_kit = EmergencyKit.find(params[:emergency_kit_id])
  end
  
  def set_kit_item
    @kit_item = @emergency_kit.kit_items.find(params[:id])
  end
  
  def kit_item_params
    params.require(:kit_item).permit(:name, :quantity, reminders_attributes: [:expiration_date])
  end
end

app/controllers/stocks/stocks_controller.rb
class Stocks::StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  def index
    @stocks = current_user.stocks
  end

  def destroy
    @stock.destroy
    redirect_to stocks_stocks_path, notice: 'Stock was successfully destroyed.'
  end

  def new
    @stock = Stock.new
    # stock_items と reminders をビルド
    @stock.stock_items.build.reminders.build
  end

  def create
    @stock = Stock.new(stock_params)
    @stock.user = current_user

    if @stock.save
      redirect_to stocks_stocks_path, notice: '備蓄アイテムが登録されました。'
    else
      Rails.logger.debug @stock.errors.full_messages # デバッグ用: エラー内容をログに出力
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @stock = Stock.find(params[:id])
    # stock_items と reminders がすでに存在していない場合のみビルド
    @stock.stock_items.build if @stock.stock_items.empty?
    @stock.stock_items.each do |stock_item|
      stock_item.reminders.build if stock_item.reminders.empty?
    end
  end

  def update
    if @stock.update(stock_params)
      redirect_to stocks_stocks_path, notice: 'アイテムが更新されました。'
    else
      Rails.logger.debug @stock.errors.full_messages # デバッグ用: エラー内容をログに出力
      render :edit, status: :unprocessable_entity
    end
  end  

  private

  def stock_params
    params.require(:stock).permit(
      :body,
      stock_items_attributes: [
        :id, :name, :quantity, :storage, :_destroy,
        reminders_attributes: [:id, :expiration_date, :interval_months, :_destroy]
      ]
    )
  end  

  def set_stock
    @stock = Stock.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      # ユーザーを保存後に認証メールを送信
      @user.send_confirmation_instructions
      redirect_to confirmation_sent_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id]) 
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ストックサポーター</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "turbo", type: "module" %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render 'shared/header_signed_in' %> <!-- ログイン後のヘッダー -->
    <% else %>
      <%= render 'shared/header_signed_out' %> <!-- ログイン前のヘッダー -->
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer id='footer' class='footer-bottom'>
  <div class='container'>
    <div class='row'>
      <div class='col-sm-6 col-12'>
        <div class='copyright'>
          <p>Copyright © 2024. A.M</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation navbar-light bg-light'>
    <%= link_to '/', class: 'navbar-brand' do %>
      <%= image_tag 'logo.png', width: '180', height: '80' %>
    <% end %>

   <div class="container">
     <nav>
       <ul class="nav navbar-nav navbar-right">
         <li><%= link_to "すべて",   '#' %></li>
         <li><%= link_to "備蓄",   '#' %></li>
         <li><%= link_to "防災バッグ", '#' %></li>
         <li><%= link_to "掲示板",   '#' %></li>
         <li><%= link_to "マイページ", '#' %></li>
        </ul>
     </nav>
   </div>
  </nav>
</header>

app/views/shared/_header_signed_in.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation navbar-light bg-light'>
    <%= link_to '/', class: 'navbar-brand' do %>
      <%= image_tag 'logo.png', width: '180', height: '80' %>
    <% end %>

    <div class="container">
      <nav>
        <ul class="header">
          <li><%= link_to "備え一覧", all_stocks_emergency_kits_path %></li>
          <li><%= link_to "備蓄", stocks_stocks_path %></li>
          <li><%= link_to "防災バッグ", stocks_emergency_kits_path %></li>
          <li><%= link_to "掲示板",   '#' %></li>
          <li><%= link_to "マイページ", user_path(current_user) %></li>
        </ul>
      </nav>
    </div>
  </nav>
</header>

app/views/shared/_header_signed_out.html.erb
<header>
  <nav class='navbar navbar-expand-lg navigation navbar-light bg-light'>
    <%= link_to '/', class: 'navbar-brand' do %>
      <%= image_tag 'logo.png', width: '180', height: '80' %>
    <% end %>
  </nav>
</header>