config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  root 'static_pages#top'
  get 'static_pages/top', to: 'static_pages#top', as: 'static_pages_top'
  get 'static_pages/welcome', to: 'static_pages#welcome'
  get 'signup', to: 'users#new'

  resources :users, only: [:show]
  
  namespace :stocks do
    resources :stocks, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :emergency_kits, only: [:index, :show, :create, :edit, :update, :destroy, :new] do
      collection do
        get 'all'
      end
      resources :kit_items, only: [:index, :create, :edit, :update, :destroy] do
      end
    end
  end  
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :user
  has_many :stock_items, dependent: :destroy 
  accepts_nested_attributes_for :stock_items  # StockItem をネストして受け入れる
  has_many :reminders, through: :stock_items
  accepts_nested_attributes_for :reminders
end

app/controllers/stocks/all_stocks_controller.rb
class Stocks::AllController < ApplicationController
  def all
    @stocks = Stock.all
    @emergency_kits = EmergencyKit.all
  end
end

app/controllers/stocks/emergency_kits_controller.rb
class Stocks::EmergencyKitsController < ApplicationController
  before_action :set_emergency_kit, only: [:show, :edit, :update, :destroy]

  def index
    @emergency_kits = EmergencyKit.where(user: current_user) # ユーザーの防災バッグを取得
  end

  def all
    @emergency_kits = EmergencyKit.where(user: current_user) # ユーザーの防災バッグ一覧を取得
    @stocks = Stock.where(user: current_user) # ユーザーの備蓄一覧を取得
  end

  def show
    # set_emergency_kit メソッドで既に @emergency_kit が設定されているため、再度 find は不要です
    @emergency_kits_owner = @emergency_kit.owner
    @kit_items = @emergency_kit.kit_items.includes(:reminders) # 関連するアイテムを取得
  end  

  def new
    @emergency_kit = EmergencyKit.new
    @gender_options = EmergencyKitsOwner.genders_i18n.invert.map { |key, value| [key, value] }
    @emergency_kit.build_reminder # Reminder を初期化
  end

  def create
    user = current_user
    gender = EmergencyKitsOwner.genders.key(emergency_kit_params[:gender])

    # パラメータを使用してオーナー情報を取得または作成
    owner = EmergencyKitsOwner.find_or_create_by(
      user_id: current_user.id,
      name: emergency_kit_params[:owner_name],
      age: emergency_kit_params[:age],
      gender: emergency_kit_params[:gender]
    )

    # EmergencyKit の作成
    @emergency_kit = EmergencyKit.new(
      user: user,
      owner: owner,
      body: emergency_kit_params[:body],
      storage: emergency_kit_params[:storage]
    )

    if @emergency_kit.save
      # 保存に成功した場合
      redirect_to stocks_emergency_kits_path, notice: 'Emergency kit was successfully created.'
    else
      # 保存に失敗した場合
      render :new
    end
  end

  def edit
    # set_emergency_kit メソッドで既に @emergency_kit が設定されているため、再度 find は不要です
  end

  def destroy
    # 関連する kit_items を削除
    @emergency_kit.kit_items.destroy_all
    
    # EmergencyKit を削除
    @emergency_kit.destroy
    
    redirect_to stocks_emergency_kits_path, notice: '防災バッグが削除されました。'
  end
  
  
  private

  def set_emergency_kit
    @emergency_kit = EmergencyKit.find(params[:id])
  end

  def emergency_kit_params
    params.require(:emergency_kit).permit(
      :storage, 
      :owner_name, 
      :age, 
      :gender, 
      reminder_attributes: [:interval_months]
    )
  end
end

app/controllers/stocks/kit_items_controller.rb
class Stocks::KitItemsController < ApplicationController
  before_action :set_emergency_kit
  before_action :set_kit_item, only: [:edit, :update, :show, :destroy]

  def index
    @kit_items = @emergency_kit.kit_items
  end

  def create
    @kit_item = @emergency_kit.kit_items.build(kit_item_params)
    if @kit_item.save
      redirect_to stocks_emergency_kit_path(@emergency_kit), notice: 'Kit item was successfully added.'
    else
      redirect_to stocks_emergency_kit_path(@emergency_kit), alert: 'Failed to add kit item.'
    end
  end
  
  def edit
  end  
  
  def update
    if @kit_item.update(kit_item_params)
      redirect_to stocks_emergency_kit_path(@kit_item.emergency_kit), notice: 'アイテムが更新されました。'
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @kit_item.destroy
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@kit_item) }
      format.html { redirect_to stocks_emergency_kit_path(@kit_item.emergency_kit), notice: "Item was successfully destroyed." }
    end
  end
  
  
  private
  
  def set_emergency_kit
    @emergency_kit = EmergencyKit.find(params[:emergency_kit_id])
  end
  
  def set_kit_item
    @kit_item = @emergency_kit.kit_items.find(params[:id])
  end
  
  def kit_item_params
    params.require(:kit_item).permit(:name, :quantity, reminders_attributes: [:expiration_date])
  end
end

app/controllers/stocks/stocks_controller.rb
class Stocks::StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  def index
    @stocks = current_user.stocks
  end

  def destroy
    @stock.destroy
    redirect_to stocks_stocks_path, notice: 'Stock was successfully destroyed.'
  end

  def new
    @stock = Stock.new
    # stock_items と reminders をビルド
    @stock.stock_items.build.reminders.build
  end

  def create
    @stock = Stock.new(stock_params)
    @stock.user = current_user

    if @stock.save
      redirect_to stocks_stocks_path, notice: '備蓄アイテムが登録されました。'
    else
      Rails.logger.debug @stock.errors.full_messages # デバッグ用: エラー内容をログに出力
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @stock = Stock.find(params[:id])
    # stock_items と reminders がすでに存在していない場合のみビルド
    @stock.stock_items.build if @stock.stock_items.empty?
    @stock.stock_items.each do |stock_item|
      stock_item.reminders.build if stock_item.reminders.empty?
    end
  end

  def update
    if @stock.update(stock_params)
      redirect_to stocks_stocks_path, notice: 'アイテムが更新されました。'
    else
      Rails.logger.debug @stock.errors.full_messages # デバッグ用: エラー内容をログに出力
      render :edit, status: :unprocessable_entity
    end
  end  

  private

  def stock_params
    params.require(:stock).permit(
      :body,
      stock_items_attributes: [
        :id, :name, :quantity, :storage, :_destroy,
        reminders_attributes: [:id, :expiration_date, :interval_months, :_destroy]
      ]
    )
  end  

  def set_stock
    @stock = Stock.find(params[:id])
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/stocks/edit.html.erb
<%= form_with model: @stock, url: stocks_stock_path(@stock), local: true do |f| %>
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-lg-8 mx-auto">
        <h1>備蓄アイテム編集</h1>

        <% if @stock.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>
            <ul>
              <% @stock.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <%= f.fields_for :stock_items do |stock_item_fields| %>
          <div class="mb-3">
            <%= stock_item_fields.label :name, "アイテム名", class: "form-label" %>
            <%= stock_item_fields.text_field :name, class: "form-control", autocomplete: "off" %>
          </div>
          <div class="mb-3">
            <%= stock_item_fields.label :quantity, "ストック数", class: "form-label" %>
            <%= stock_item_fields.number_field :quantity, class: "form-control", autocomplete: "off" %>
          </div>
          <div class="mb-3">
            <%= stock_item_fields.label :storage, "保管場所", class: "form-label" %>
            <%= stock_item_fields.text_field :storage, class: "form-control", autocomplete: "off" %>
          </div>
        <% end %>
        <%= f.submit "備蓄アイテムの更新", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/stocks/stocks/index.html.erb
<h1 class="page-title1">備蓄アイテム一覧</h1>

<% if @stocks.present? %>
  <div class="inner_container">
    <nav>
      <ul class="nav navbar-nav navbar-left">
        <% @stocks.each do |stock| %>
          <li>
            <div style="text-align: left;">
              <% stock.stock_items.each do |item| %>
                <strong><%= item.name %></strong>
                <br>ストック数: <%= item.quantity %>
                <br>保管場所: <%= item.storage %>
              <% end %>
            </div>
            <div class="button-container3">
              <%= link_to "編集", edit_stocks_stock_path(stock), class: 'btn btn-secondary' %>
              <%= link_to '削除', stocks_stock_path(stock), method: :delete, data: { confirm: '本当に削除しますか？', turbo_method: :delete } , class: 'btn btn-danger'%>
            </div>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
  <%= image_tag 'top.jpg', style: 'width: 300px; height: 350px; position: absolute; top: 400px; left: 1100px; pointer-events: none;' %>
  <div class="inner_container">
    <nav>
      <div class="button-container-stock">
        <li><%= link_to "新しいアイテムを追加", new_stocks_stock_path, class: 'btn btn-primary custom-btn' %></li>
      </div>
    </nav>
  </div>
<% else %>
  <p class="noitem">備蓄アイテムは一つもありません...</p>
  <%= image_tag 'nostock.png', style: 'width: 450px; height: 500px; position: absolute; top: 300px; left: 500px;' %>
  <div class="inner_container-noitem">
    <nav>
      <ul class="nav navbar-nav navbar-left2">
        <li><%= link_to "新しいアイテムを追加", new_stocks_stock_path, class: 'btn btn-noitem custom-btn' %></li>
      </ul>
    </nav>
  </div>
<% end %>

app/views/stocks/stocks/new.html.erb
<%= form_with model: @stock, url: stocks_stocks_path do |f| %>
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-lg-8 mx-auto">
        <h1>備蓄アイテム登録</h1>

        <% if @stock.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>
            <ul>
              <% @stock.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
        </div>
      <% end %>
        
      <%= f.fields_for :stock_items do |stock_item_fields| %>
        <div class="mb-3">
          <%= stock_item_fields.label :stock_item_name, "アイテム名", class: "form-label" %>
          <%= stock_item_fields.text_field :name, class: "form-control", autocomplete: "off" %>
        </div>
        <div class="mb-3">
          <%= stock_item_fields.label :quantity, "ストック数", class: "form-label" %>
          <%= stock_item_fields.number_field :quantity, class: "form-control", autocomplete: "off" %>
        </div>
        <div class="mb-3">
          <%= stock_item_fields.label :storage, "保管場所", class: "form-label" %>
          <%= stock_item_fields.text_field :storage, class: "form-control", autocomplete: "off" %>
        </div>
      <% end %>

      <%= f.fields_for :reminders do |reminder_fields| %>
        <div class="mb-3">
          <%= reminder_fields.label :expiration_date, "期限", class: "form-label" %>
          <%= reminder_fields.date_field :expiration_date, class: "form-control", autocomplete: "off" %>
        </div>

        <div class="mb-3">
          <%= reminder_fields.label :interval_months, "かくにんサイクル（月単位）", class: "form-label" %>
          <%= reminder_fields.number_field :interval_months, class: "form-control", autocomplete: "off" %>
        </div>
      <% end %>

      <%= f.submit "備蓄アイテムの登録", class: "btn btn-primary" %>
    </div>
  </div>
</div>
<% end %>